
name: Python Application CI/CD to Azure

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: '1. Checkout code'
      uses: actions/checkout@v4

    - name: '2. Set up Python 3.10'
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: '3. Install dependencies'
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: '4. Lint with flake8'
      run: |
        # para a esteira se houver erros de sintaxe
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # apenas avisa sobre complexidade e tamanho da linha
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: '5. Test with pytest'
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
    - name: '1. Checkout code'
      uses: actions/checkout@v4

    - name: '2. Set up Python 3.10'
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: '3. Install dependencies (for packaging)'
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: '4. Deploy to Azure Function App'
      uses: Azure/functions-action@v1 
      with:
        app-name: 'senaclabazurefunction'
        package: '.' 

        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
